### ISSUE TITLE
Run cargo fix

### ISSUE THREAD

**Issue by stevefan1999-personal** [xfbs/imstr#4]
I see there are a lot of warnings. Have you considered running `cargo fix`?

**Comment by xfbs** [comment]
I pushed some code yesterday to take care of some warnings (they were there because I had imported some traits but forgot to `impl` them), but some remain. 

Also some missing documentation in places.

**Comment by xfbs** [comment]
I've squashed pretty much all warnings! Some missing in `tests/string.rs`. Will close this for now.
